services:
  mongodb:
    image: mongo:6.0
    container_name: weibo-mongo
    volumes:
      - ./db_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
    container_name: weibo-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - JWT_SECRET_KEY=your_secret_key_here
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    container_name: weibo-frontend
    ports:
      - "3030:3000"
    depends_on:
      - backend

